### ISSUE TITLE
EROFS: read-only file system error

### ISSUE THREAD

**Issue by TakodaS** [covid-modeling/model-runner#51]
On Ubuntu 18.04 when i try to `run-model` under `packages/model-runner` with `npm -v` 6.14.5 and `node -v` 14.3.0:

```bash
$ sudo docker-compose run run-model
[2020-06-01 14:29:03.612 +0000] INFO  (model-runner on acba2702b599): {"id":"my-model-run-id","callbackURL":null,"models":[{"slug":"mrc-ide-covid-sim","imageURL":"docker.pkg.github.com/covid-modeling/model-runner/mrc-ide-covidsim-connector:master"}],"configuration":{"region":"US","subregion":"US-WY","parameters":{"calibrationDate":"2020-04-18","calibrationCaseCount":1400,"calibrationDeathCount":200,"r0":null,"interventionPeriods":[{"startDate":"2020-03-15","reductionPopulationContact":15,"socialDistancing":"moderate"},{"startDate":"2020-03-21","reductionPopulationContact":65,"socialDistancing":"moderate","schoolClosure":"aggressive"},{"startDate":"2020-03-25","reductionPopulationContact":90,"socialDistancing":"aggressive","schoolClosure":"aggressive"},{"startDate":"2020-05-01","reductionPopulationContact":50,"socialDistancing":"moderate","schoolClosure":"mild"},{"startDate":"2020-06-01","reductionPopulationContact":0}]}}}
[2020-06-01 14:29:03.614 +0000] ERROR (model-runner on acba2702b599): EROFS: read-only file system, open '/data/input/inputFile.json'
    Error: EROFS: read-only file system, open '/data/input/inputFile.json'
        at Object.openSync (fs.js:461:3)
        at Object.writeFileSync (fs.js:1387:35)
        at main (/runner/packages/model-runner/dist/src/main.js:66:12)
        at Object.<anonymous> (/runner/packages/model-runner/dist/src/main.js:145:1)
        at Module._compile (internal/modules/cjs/loader.js:1200:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
        at Module.load (internal/modules/cjs/loader.js:1049:32)
        at Function.Module._load (internal/modules/cjs/loader.js:937:14)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
        at internal/main/run_main_module.js:17:47
```

I also tried with the `node:14` docker image and got the same error.

EDIT: When I try to manually make the build I run into another error. After `make bootstrap && make build && make test` run fine I get:

```bash
 sudo ./bin/run-model input/input.json 
npx: installed 35 in 3.234s
/home/ab/azure-covid-sim/austen-model-runner/packages/model-runner/dist/src/blobstore.js:38
        for await (const entry of stream) {
            ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ab/azure-covid-sim/austen-model-runner/packages/model-runner/dist/src/main.js:7:21)
```

**Comment by TakodaS** [comment]
I fixed this by changing the permissions in `packages/model-runner/docker-compose.yaml`  on line 33 

`- ./test/test-job-mrc-ide-covidsim.json:/data/input/inputFile.json:ro`
`+ ./test/test-job-mrc-ide-covidsim.json:/data/input/inputFile.json:rw`

But obviously this isn't a great fix, since there is no reason the input `.json` file should have write permissions. Alas, it appears docker has issues with it being read only.

**Comment by aeisenberg** [comment]
It's on purpose that we are writing to the input file. When we run the model-runner on our servers, the input is coming from a different (and temporary) location and we need to store the inputs to keep track of how this particular instance of the runner was invoked.

It just happens to be that when you run the model-runner through docker-compose, it reads and writes to the same location. So, currently there is a bug in the docker-compose and thank you for finding it. I'll create a fix for this.

As for your `SyntaxError: Unexpected reserved word` error, that would only happen if you are running under node < v10.0. Please make sure you have an up to date version.

**Comment by TakodaS** [comment]
Your new branch still overwrites `inputFile.json`  resulting in the same error if your run `docker-compose run run-model` twice.

**Comment by TakodaS** [comment]
Your new branch still overwrites `inputFile.json` if you run it twice, leading to an error.

Right now I am running into problems with docker permissions, specifically getting `HTTP code 500: no basic auth credits` when running `docker-compose run run-model`. I will try to fix it but what is strange is that I have the correct GitHub authentication because I can `docker pull` your model-runner package with no problem. Does `docker-compose` use different permissions to `docker`?

**Comment by TakodaS** [comment]
I fixed the above by adding login info to the `DOCKER_USER` and `DOCKER_PASSWORD` fields in `docker-compose.yaml`.

Now the model-runner runs but gives me an error at the output:
```bash
 Error: ENOENT: no such file or directory, open '/data/output/data.json'
        at Object.openSync (fs.js:461:3)
        at Object.readFileSync (fs.js:364:35)
        at Object.enforceOutputSchema (/runner/packages/model-runner/dist/src/schema.js:19:27)
        at main (/runner/packages/model-runner/dist/src/main.js:91:18)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
